
stages:
  - build
  - test

build:
  stage: build
  image: node:16-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

test:
  image: alpine
  stage: test
  dependencies:
    - build
  script:
    - test -f build/index.html 

unit tests:
  image: node:16-alpine
  stage: test
  script:
    - npm install
    - npm test