
stages:
  - build
  - test

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - NODE_OPTIONS=--openssl-legacy-provider npm run build
  artifacts:
    paths:
      - build/

test:
  image: node:20-alpine
  stage: test
  dependencies:
    - build
  script:
    - npm install -g serve
    - serve -s build

unit tests:
  image: node:16-alpine
  stage: test
  script:
    - npm install
    - npm test