
stages:
  - build
  - test

build:
  stage: build
  image: node:16-alpine
  script:
    - npm install
    - npm run build
    - ls -la build/  
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

test:
  image: alpine
  stage: test
  dependencies:
    - build
  script:
    - ls -la  
    - ls -la build/ || echo "Build directory not found"
    - test -f build/index.html || echo "index.html not found in build directory"